
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author manun
 */
public class checking extends javax.swing.JFrame {


    /**
     * Creates new form checking
     */
    public checking() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        register = new javax.swing.ButtonGroup();
        bdate = new com.toedter.calendar.JDateChooser();
        f = new javax.swing.JTextField();
        l = new javax.swing.JTextField();
        mi = new javax.swing.JTextField();
        city = new javax.swing.JComboBox<>();
        bansa = new javax.swing.JComboBox<>();
        father = new javax.swing.JTextField();
        mother = new javax.swing.JTextField();
        br = new javax.swing.JTextField();
        copies = new javax.swing.JTextField();
        araw = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        babae = new javax.swing.JRadioButton();
        lalaki = new javax.swing.JRadioButton();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        birthcert = new javax.swing.JRadioButton();
        marriage = new javax.swing.JRadioButton();
        cenomar = new javax.swing.JRadioButton();
        death = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 360, -1));

        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 370, -1));
        getContentPane().add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 370, -1));
        getContentPane().add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 360, -1));

        city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Alaminos", "Angeles", "Antipolo", "Bacolod", "Bacoor", "Bago", "Baguio", "Bais", "Balanga", "Batangas", "Bayawan", "Baybay", "Bayugan", "Biñan", "Bislig", "Bogo", "Borongan", "Butuan", "Cabadbaran", "Cabanatuan", "Cabuyao", "Cadiz", "Cagayan de Oro", "Calamba", "Calapan", "Calbayog", "Candon", "Canlaon", "Carcar", "Catbalogan", "Cavite", "Cebu", "Cotabato", "Dagupan", "Danao", "Dapitan", "Dasmariñas", "Davao", "Digos", "Dipolog", "Dumaguete", "El Salvador", "Escalante", "Gapan", "General Santos", "General Trias", "Gingoog", "Guihulngan", "Himamaylan", "Ilagan", "Iloilo", "Imus", "Iriga", "Isabela", "Kabankalan", "Kidapawan", "Koronadal", "La Carlota", "Laoag", "Lapu-Lapu", "Las Piñas", "Legazpi", "Ligao", "Lipa", "Lucban", "Lucena", "Maasin", "Mabalacat", "Makati", "Malabon", "Malaybalay", "Malolos", "Mandaluyong", "Mandaue", "Manila", "Marawi", "Marikina", "Masbate", "Meycauayan", "Muñoz", "Muntinlupa", "Naga", "Navotas", "Olongapo", "Ormoc", "Oroquieta", "Ozamiz", "Pagadian", "Palayan", "Panabo", "Parañaque", "Pasay", "Pasig", "Passi", "Puerto Princesa", "Quezon City", "Roxas", "Sagay", "San Carlos", "San Fernando", "San Jose", "San Jose del Monte", "San Juan", "San Pablo", "Santa Rosa", "Santiago", "Silay", "Sipalay", "Sorsogon", "Surigao", "Tabaco", "Tacloban", "Tacurong", "Tagaytay", "Tagbilaran", "Taguig", "Tagum", "Talisay", "Tanauan", "Tanjay", "Tarlac", "Tayabas", "Toledo", "Tuguegarao", "Urdaneta", "Valencia", "Valenzuela", "Victorias", "Vigan", "Zamboanga" }));
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 360, 20));

        bansa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Abra", "Agusan del Norte", "Agusan del Sur", "Aklan", "Albay", "Antique", "Apayao", "Aurora", "Basilan", "Bataan", "Batanes", "Batangas", "Benguet", "Biliran", "Bohol", "Bukidnon", "Bulacan", "Cagayan", "Camarines Norte", "Camarines Sur", "Camiguin", "Capiz", "Catanduanes", "Cavite", "Cebu", "Compostela Valley", "Cotabato", "Davao del Norte", "Davao del Sur", "Davao Occidental", "Davao Oriental", "Dinagat Islands", "Eastern Samar", "Guimaras", "Ifugao", "Ilocos Norte", "Ilocos Sur", "Iloilo", "Isabela", "Kalinga", "La Union", "Laguna", "Lanao del Norte", "Lanao del Sur", "Leyte", "Maguindanao", "Marinduque", "Masbate", "Misamis Occidental", "Misamis Oriental", "Mountain Province", "Negros Occidental", "Negros Oriental", "Northern Samar", "Nueva Ecija", "Nueva Vizcaya", "Occidental Mindoro", "Oriental Mindoro", "Palawan", "Pampanga", "Pangasinan", "Quezon", "Quirino", "Rizal", "Romblon", "Samar", "Sarangani", "Siquijor", "Sorsogon", "South Cotabato", "Southern Leyte", "Sultan Kudarat", "Sulu", "Surigao del Norte", "Surigao del Sur", "Tarlac", "Tawi-Tawi", "Zambales", "Zamboanga del Norte", "Zamboanga del Sur", "Zamboanga Sibugay", "Metro Manila (National Capital Region)" }));
        getContentPane().add(bansa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 360, 20));
        getContentPane().add(father, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 320, -1));
        getContentPane().add(mother, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 320, -1));
        getContentPane().add(br, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, -1));
        getContentPane().add(copies, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 132, 160, 30));
        getContentPane().add(araw, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 160, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 100, 40));

        next.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        next.setText("PROCEED");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, 100, 40));

        Gender.add(babae);
        getContentPane().add(babae, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        Gender.add(lalaki);
        lalaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalakiActionPerformed(evt);
            }
        });
        getContentPane().add(lalaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 30, 20));

        buttonGroup1.add(yes);
        getContentPane().add(yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, -1));

        buttonGroup1.add(no);
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, -1, -1));

        register.add(birthcert);
        getContentPane().add(birthcert, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, 30));

        register.add(marriage);
        getContentPane().add(marriage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 579, -1, 30));

        register.add(cenomar);
        getContentPane().add(cenomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 579, 50, 30));

        register.add(death);
        getContentPane().add(death, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 579, 20, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\manun\\Downloads\\7 (1).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 620, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

       if(br.getText().length()<=0 || copies.getText().length()<=0 || f.getText().length()<=0 || l.getText().length()<=0 || mi.getText().length()<=0 || father.getText().length()<=0  || mother.getText().length()<=0){
             JOptionPane.showMessageDialog(null, "Complete the form!!");
         }
       else{
           new last().setVisible(true);
       }
        
    }//GEN-LAST:event_nextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Component frame = null;
        
         if(JOptionPane.showConfirmDialog(frame,"Are you sure you want to clear?", "CLEAR", 
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION) 
            {
               f.setText("");
               l.setText("");
               mi.setText("");
               father.setText("");
               mother.setText("");
               br.setText("");
               copies.setText("");
               city.setSelectedIndex(0);
               bansa.setSelectedIndex(0);
            }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed

    }//GEN-LAST:event_cityActionPerformed

    private void lalakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lalakiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup Gender;
    public static com.toedter.calendar.JDateChooser araw;
    public static javax.swing.JRadioButton babae;
    public static javax.swing.JComboBox<String> bansa;
    public static com.toedter.calendar.JDateChooser bdate;
    public static javax.swing.JRadioButton birthcert;
    public static javax.swing.JTextField br;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JRadioButton cenomar;
    public static javax.swing.JComboBox<String> city;
    public static javax.swing.JTextField copies;
    public static javax.swing.JRadioButton death;
    public static javax.swing.JTextField f;
    public static javax.swing.JTextField father;
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField l;
    public static javax.swing.JRadioButton lalaki;
    public static javax.swing.JRadioButton marriage;
    public static javax.swing.JTextField mi;
    public static javax.swing.JTextField mother;
    private javax.swing.JButton next;
    public static javax.swing.JRadioButton no;
    private javax.swing.ButtonGroup register;
    public static javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
}
