
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author manun
 */
public class info extends javax.swing.JFrame {

    /**
     * Creates new form info
     */
    info() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        miin = new javax.swing.JTextField();
        datebirth = new javax.swing.JTextField();
        birthplace = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        tatay = new javax.swing.JTextField();
        nanay = new javax.swing.JTextField();
        reference = new javax.swing.JTextField();
        kopya = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        kukuha = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        oras = new javax.swing.JTextField();
        kasarian = new javax.swing.JTextField();
        reg = new javax.swing.JTextField();
        request = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fname.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        fname.setEnabled(false);
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 390, -1));

        lname.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lname.setEnabled(false);
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 390, -1));

        miin.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        miin.setEnabled(false);
        getContentPane().add(miin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 380, -1));

        datebirth.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        datebirth.setEnabled(false);
        getContentPane().add(datebirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 380, -1));

        birthplace.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        birthplace.setEnabled(false);
        getContentPane().add(birthplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 380, -1));

        country.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        country.setEnabled(false);
        getContentPane().add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 380, -1));

        tatay.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tatay.setEnabled(false);
        getContentPane().add(tatay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 493, 340, 30));

        nanay.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        nanay.setEnabled(false);
        getContentPane().add(nanay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 340, 30));

        reference.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        reference.setEnabled(false);
        getContentPane().add(reference, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, -1));

        kopya.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        kopya.setEnabled(false);
        getContentPane().add(kopya, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 50, 30));

        date.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        date.setEnabled(false);
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 80, 30));

        kukuha.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        kukuha.setEnabled(false);
        getContentPane().add(kukuha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 190, 30));

        logout.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, -1, 50));

        exit.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 110, 50));

        oras.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        oras.setEnabled(false);
        oras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orasActionPerformed(evt);
            }
        });
        getContentPane().add(oras, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 90, 30));

        kasarian.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        kasarian.setEnabled(false);
        kasarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasarianActionPerformed(evt);
            }
        });
        getContentPane().add(kasarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 380, 30));

        reg.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        reg.setEnabled(false);
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 120, -1));

        request.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        request.setEnabled(false);
        getContentPane().add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 410, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\manun\\Downloads\\9 (1).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        JFrame frame = new JFrame("AGAIN");
        if(JOptionPane.showConfirmDialog(frame,"Do you want to try again?", "AGAIN",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
    {
        new LoginFrame().setVisible(true);
        this.setVisible(false);
        }
        else
        {
            System.exit(0);
        }

    }//GEN-LAST:event_logoutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JFrame frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit", "EXIT",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
    {
        System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void orasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orasActionPerformed

    private void kasarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasarianActionPerformed
     
    }//GEN-LAST:event_kasarianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField birthplace;
    public static javax.swing.JTextField country;
    public static javax.swing.JTextField date;
    public static javax.swing.JTextField datebirth;
    private javax.swing.JButton exit;
    public static javax.swing.JTextField fname;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField kasarian;
    public static javax.swing.JTextField kopya;
    public static javax.swing.JTextField kukuha;
    public static javax.swing.JTextField lname;
    private javax.swing.JButton logout;
    public static javax.swing.JTextField miin;
    public static javax.swing.JTextField nanay;
    public static javax.swing.JTextField oras;
    public static javax.swing.JTextField reference;
    public static javax.swing.JTextField reg;
    public static javax.swing.JTextField request;
    public static javax.swing.JTextField tatay;
    // End of variables declaration//GEN-END:variables
}
