

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author manun
 */
public class last extends javax.swing.JFrame {

    /**
     * Creates new form last
     */
    public last() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        time = new javax.swing.JComboBox<>();
        pick = new com.toedter.calendar.JDateChooser();
        recipient = new javax.swing.JTextField();
        owner = new javax.swing.JComboBox<>();
        balik = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        time.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "8:00 AM - 9:00 AM", "9:00 AM - 10:00 AM", "10:00 AM - 11:00 AM", "11:00 AM - 12:00 PM", "1:00 PM - 2:00 PM", "2:00 PM - 3:00 PM", "3:00 AM - 4:00 PM", "4:00 AM - 5:00 PM", "5:00 AM - 6:00 PM", "6:00 AM - 7:00 PM" }));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 260, 30));
        getContentPane().add(pick, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 260, 30));
        getContentPane().add(recipient, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 260, 30));

        owner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        owner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Owner", "Parent", "Child", "Guardian/ Representative" }));
        getContentPane().add(owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 260, 40));

        balik.setBackground(new java.awt.Color(153, 153, 255));
        balik.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        balik.setText("RETURN");
        balik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balikActionPerformed(evt);
            }
        });
        getContentPane().add(balik, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 100, 60));

        next.setBackground(new java.awt.Color(153, 153, 255));
        next.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        next.setText("PROCEED");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 100, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\manun\\Downloads\\4.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void balikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balikActionPerformed
      new checking().setVisible(true);
    }//GEN-LAST:event_balikActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
 new info().setVisible(true);
        
       String First =" ";
       String Middle= " ";
       String Last = " ";
       String Fa= " ";
       String Ma= " ";
       String Ref= " ";
       String Cop= " ";
       
       String selectedcity = checking.city.getSelectedItem().toString();
        info.birthplace.setText(selectedcity);
        String selectedbansa = checking.bansa.getSelectedItem().toString();
        info.country.setText(selectedbansa);
        String selectedtime = time.getSelectedItem().toString();
         info.oras.setText(selectedtime);
         String selectedrecipient = owner.getSelectedItem().toString();
         info.kukuha.setText(selectedrecipient); 
         
        
        First=checking.f.getText();
        info.fname.setText("" +First);
        
        Middle=checking.mi.getText();
        info.miin.setText("" +Middle);
        
        Last=checking.l.getText();
        info.lname.setText("" +Last);
        
        Middle=checking.mi.getText();
        info.miin.setText("" +Middle);
        
        Fa=checking.father.getText();
        info.tatay.setText("" +Fa);
        
        Ma=checking.mother.getText();
        info.nanay.setText("" +Ma);
        
        Ref=checking.br.getText();
        info.reference.setText("" +Ref);
        
        Cop=checking.copies.getText();
        info.kopya.setText("" +Cop);
        
        String dates =((JTextField)checking.bdate.getDateEditor().getUiComponent()).getText();
        info.datebirth.setText(dates);
        
        String kuha =((JTextField)last.pick.getDateEditor().getUiComponent()).getText();
        info.date.setText(kuha);
        
        String gender= " ";
        if(checking.lalaki.isSelected())
        {
            gender = "Male";
        }
        else if (checking.babae.isSelected())
        {
            gender = "Female";
        }
        else
        {
            gender = "N/A";
        }
        
        info.kasarian.setText(gender);
        
        String registre= " ";
        if(checking.yes.isSelected())
        {
            registre = "Yes";
        }
        else if(checking.no.isSelected())
        {
            registre = "No";
        }
        
        info.reg.setText(registre);

        String request= " ";
         if(checking.birthcert.isSelected())
        {
            request = "Birth Certificate";
        }
        else if(checking.marriage.isSelected())
        {
            request = "Marriage Certificate";
        }
         else if(checking.cenomar.isSelected())
        {
            request = "CENOMAR";
        }
        else if(checking.death.isSelected())
        {
            request = "Death Certificate";
        }
        info.request.setText(request);
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(last.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(last.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(last.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(last.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new last().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balik;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton next;
    private javax.swing.JComboBox<String> owner;
    public static com.toedter.calendar.JDateChooser pick;
    private javax.swing.JTextField recipient;
    private javax.swing.JComboBox<String> time;
    // End of variables declaration//GEN-END:variables

    private Object getDateEditor() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void Uicomponent() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void getText() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
