
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author manun
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hidepass = new javax.swing.JLabel();
        seepass = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        upass = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Frame");
        getContentPane().setLayout(null);

        hidepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1315548-removebg-preview (1).png"))); // NOI18N
        hidepass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidepassMousePressed(evt);
            }
        });
        getContentPane().add(hidepass);
        hidepass.setBounds(530, 360, 50, 50);

        seepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1315513-removebg-preview (1).png"))); // NOI18N
        seepass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seepassMousePressed(evt);
            }
        });
        getContentPane().add(seepass);
        seepass.setBounds(530, 370, 50, 30);

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        getContentPane().add(uname);
        uname.setBounds(290, 310, 290, 30);

        upass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upassActionPerformed(evt);
            }
        });
        getContentPane().add(upass);
        upass.setBounds(290, 370, 290, 30);

        login.setBackground(new java.awt.Color(153, 153, 255));
        login.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(370, 510, 124, 40);

        exit.setBackground(new java.awt.Color(153, 153, 255));
        exit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(460, 450, 100, 39);

        clear.setBackground(new java.awt.Color(153, 153, 255));
        clear.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(300, 450, 100, 39);

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 3, 10)); // NOI18N
        jButton1.setText("CREATE YOUR OWN ACCOUNT");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 400, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\manun\\Downloads\\3.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 700);

        setSize(new java.awt.Dimension(676, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        Component frame = null;
        
        if(JOptionPane.showConfirmDialog(frame,"Are you sure you want to clear?", "CLEAR", 
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION) 
    {
        uname.setText("");
        upass.setText("");
    }     
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    JFrame frame = new JFrame("EXIT");
    if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit", "EXIT", 
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION) 
    {
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    }
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String user = uname.getText();
        String pass = upass.getText();

        if(user.equals("zdtmanungay") && pass.equals("BSIT-1FL"))
        {
            new checking().setVisible(true);
            this.setVisible(false);
        }
        else if(user.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter a username!!");
        }
        else if(pass.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Enter a password!!");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Your username and password did not match!!");
        }
        
       
    }//GEN-LAST:event_loginActionPerformed

    private void upassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upassActionPerformed

    private void hidepassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidepassMousePressed

        seepass.setVisible(true);
        hidepass.setVisible(false);
        upass.setEchoChar((char)0);
    }//GEN-LAST:event_hidepassMousePressed

    private void seepassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seepassMousePressed
        
        seepass.setVisible(false);
        hidepass.setVisible(true);
        upass.setEchoChar('*');
        
    }//GEN-LAST:event_seepassMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        regform rgf = new regform();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton exit;
    private javax.swing.JLabel hidepass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel seepass;
    public static javax.swing.JTextField uname;
    public static javax.swing.JPasswordField upass;
    // End of variables declaration//GEN-END:variables

    private void getText() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
